Repository terra-money/core, pull requests merged in 2023-05, with the labels that each got.

#131 fix: alliance amino signatures
  go.mod
  go.sum
Labels: bug

#135 feat: migration and version chaning
  app/app.go
  app/config/const.go
  app/upgrades/v2.4/upgrade.go
  client/docs/config.json
  client/docs/swagger-ui/swagger.yaml
  scripts/chain-upgrade-tester/chain-upgrade.sh
Labels: enhancement

#141 fix: ibc-hooks callback not triggering wasm callback
  app/app.go
  x/ibc-hooks/wasm_hook.go
Labels: bug, breaking changes
